name: flutter_to_do
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^1.3.4
  retrofit_generator: ^1.3.4+2
  dio: ^3.0.9
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  provider: ^4.3.2+1
  get_it: ^4.0.2
  pull_to_refresh: ^1.5.8
  logger: ^0.9.1
  encrypted_shared_preferences: ^1.0.5
  flutter_multi_formatter: ^1.1.6
  flutter_money_formatter: ^0.8.3
  flutter_spinkit: ^4.1.2
  fluttertoast: ^4.0.1
  route_annotation: ^0.2.0
  build_runner: ^1.10.0
  cupertino_icons: ^0.1.3
  route_generator: ^0.1.5
  font_awesome_flutter: ^8.8.1
  device_info: ^0.4.2+4
  flutter_calendar_carousel: ^1.4.12
  intl: ^0.16.1
  sqflite: ^1.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^0.39.14
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/langs/
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
  